baseURL = "/"
languageCode = "en-us"
title = "sammler.io Documentation"

theme = "hugo-material-docs"

[params]
  author = "stefanwalther"
  description = "sammler.io Documentation"
  copyright = "Released under the MIT license"
  provider = "GitHub"
  repo_url = "https://github.com/sammler/docs"

[params.palette]
  primary = "red"
  accent  = "light-green"

[social]
  twitter = "waltherstefan"
  github  = "stefanwalther"

[params.font]
	text = "Open Sans"
	code = "Inconsolata"


[[menu.main]]
	name   = "About"
	url    = "about"
	weight = 10

[[menu.main]]
	name   = "Configuration"
	url    = "configuration"
	weight = 20

[[menu.main]]
	name   = "Services"
	url    = "services"
	weight = 30


